# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-09-09 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180908_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbmscatalog',
            name='type',
            field=models.IntegerField(choices=[(1, 'MySQL'), (2, 'Postgres'), (3, 'Db2'), (4, 'Oracle'), (5, 'SQL Server'), (6, 'SQLite'), (7, 'HStore'), (8, 'Vector'), (9, 'MyRocks'), (10, 'SAPHANA')]),
        ),
    ]
